# Stage 1: Build the Angular app
FROM node:20.19.3-slim AS build

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# Install Nx CLI globally
RUN npm install -g nx

# Copy the Nx workspace
COPY . .

## Replace the placeholder backend URL at build time
#ARG BACKEND_URL=http://192.168.0.223:8080/api
#RUN sed -i "s|http://localhost:8080/api|${BACKEND_URL}|g" apps/open-event-app/src/app/service.config.ts

ENV NX_DAEMON=false
# Build the Angular app
RUN npx nx build open-event-app --configuration=development
RUN npx nx build open-event-external --configuration=development --base-href /external/

# Stage 2: Serve the Angular app with a lightweight web server
FROM nginx:1.27-alpine

# Remove the default Nginx static content
RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist/apps/open-event-app/browser /usr/share/nginx/html/app/
COPY --from=build /app/dist/apps/open-event-external/browser /usr/share/nginx/html/external/

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
