# Stage 1: Build the Angular app
FROM node:22-alpine AS build

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Install Nx CLI globally
RUN npm install -g nx

# Copy the Nx workspace
COPY . .

## Replace the placeholder backend URL at build time
#ARG BACKEND_URL=http://192.168.0.223:8080/api
#RUN sed -i "s|http://localhost:8080/api|${BACKEND_URL}|g" apps/open-event-app/src/app/service.config.ts

# Build the Angular app
RUN npx nx build open-event-app --configuration=production

# Stage 2: Serve the Angular app with a lightweight web server
FROM nginx:1.23-alpine

# Remove the default Nginx static content
RUN rm -rf /usr/share/nginx/html/*

# Copy the built Angular app from the build stage to the Nginx HTML directory
COPY --from=build /app/dist/apps/open-event-app/browser /usr/share/nginx/html

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
